### ISSUE TITLE
Normalize codebase

### ISSUE THREAD

**Issue by crusopaul** [bmos/FG-PFRPG-TotalEncumbrance#30]
Current code works as intended, but could benefit from review for possible optimizations. Additionally, documentation comments are not consistent in formatting, language, or application.

It may be over the top, but would it be worth considering the use of an autodoc system?

**Comment by bmos** [comment]
I don't know enough about autodoc systems. Care to elaborate?
Definitely room for optimization in there and some parts seem over-documented while others are clearly under-documented.

**Comment by crusopaul** [comment]
Yeah! Basically what an autodoc system would do is take comments in code and automatically create a browsable document out of it. This typically ends up in the format of a browsable HTML. I'm not aware of any preferred autodoc tools for a Lua project and want to say that an autodoc system for a XML/Lua project does not readily exist. I think if we were to use an autodoc tool it would essentially be used to document Lua functions by module. A common autodoc system is Doxygen and produces documentation like [this](https://dbus.freedesktop.org/doc/api/html/index.html). Another example would be Javadoc, that can create something like [this](https://hub.spigotmc.org/javadocs/spigot/overview-summary.html) for Java projects.

**Comment by bmos** [comment]
Do you mean like this?
https://keplerproject.github.io/luadoc/
😁

**Comment by crusopaul** [comment]
Yeah! Funny enough, I found that one this morning and noticed that it was deprecated. The replacement is now [this](https://github.com/stevedonovan/LDoc).

**Comment by bmos** [comment]
Let's do it.
