### ISSUE TITLE
Unity: armorcheckpenalyactive not active

### ISSUE THREAD

**Issue by bmos** [bmos/FG-PFRPG-TotalEncumbrance#35]
It kind of feels like it's getting overridden by the armor penalties as it only happens when the character has both types of penalties.

**Comment by bmos** [comment]
This doesn't seem to be our code acting differently, but rather the fg ruleset doing so.

**Comment by bmos** [comment]
It looks like calcItemArmorClass in manager_char.lua is normally responsible for setting armormaxstatbonusactive to 1, so this function must be getting called after applyPenalties in real_encumbrance.lua.
I'm not sure if this is because the order has changed or if something we are doing is now triggering that function inadvertently.

**Comment by bmos** [comment]
It's probably the latter.
calcItemArmorClass is called by a number of pretty common things.
onIDChanged, onBonusChanged, onArmorChanged, and onCarriedChanged

**Comment by crusopaul** [comment]
That's rough. I'm guessing the load order doesn't help?

**Comment by bmos** [comment]
I haven't tried it but AFAIK load order is for after the rulesets. Just inter-extension conflicts.
