### ISSUE TITLE
Total inventory value calculation edge cases

### ISSUE THREAD

**Issue by bmos** [bmos/FG-PFRPG-TotalEncumbrance#36]
The code to calculate the total value of everything in a player's inventory is currently rather fragile.
It gets very upset when provided with abnormal inputs. As it can be hard to figure out what item is causing it, it should either print the item name on errors or (better yet) skip that item altogether.

The most prevalent example of this is formatting such as '1 sp-100 gp'
Technically, this one is a data-entry issue, as the player or GM should enter the correct value when the item is purchased, but it would be good to ignore any item values that contain a "-".

**Comment by bmos** [comment]
The fix I'm currently testing is:
`---	Convert everything to main currency and drop any non-numerical characters. ('300gp' -> 300) ('30pp' -> 300) ('3sp' -> .3).
local function processItemCost(sItemCost)
	if string.match(sItemCost, '%-') then
		return 0
	end

	local sTrimmedItemCost = sItemCost:gsub('[^0-9.-]', '')

	if sTrimmedItemCost then
		nTrimmedItemCost = tonumber(sTrimmedItemCost)
		for k,v in pairs(TEGlobals.tDenominations) do
			if string.match(sItemCost, k) then
				return nTrimmedItemCost * v
			end
		end
	end

	return 0
end`

**Comment by crusopaul** [comment]
So I tested FG's demo campaign, it looks like it will not load any custom extensions without a sub :/.
Anyways, try something like the following:

`local function processItemCost(sItemCost)
	local nComponentSum = 0
	local nComponent
	
	for sComponent in string.gmatch(sItemCost, '%d+[ ]*%w+') do
		nComponent = tonumber(sComponent:gsub('[^0-9,-.]', ''))
		if nComponent then
			for k,v in pairs(TEGlobals.tDenominations) do
				if string.match(sComponent, k) then
					nComponentSum = nComponentSum + nComponent * v
					break
				end
			end
			nComponent = nil
		end
	end
	
	return nComponentSum
end`

This will, hopefully, add multiple denominations in strings together. For example, if you had '1sp 100 gp; 1ep' then this would sum 1sp + 100gp + 1ep = 100.60gp.

**Comment by bmos** [comment]
> So I tested FG's demo campaign, it looks like it will not load any custom extensions without a sub :/.
ooh, bummer.

**Comment by bmos** [comment]
> This will, hopefully, add multiple denominations in strings together. For example, if you had '1sp 100 gp; 1ep' then this would sum 1sp + 100gp + 1ep = 100.60gp.

That's actually not a good outcome.
The item "cards" has a value of anywhere between 1 silver piece and 100 gold pieces depending on the specific deck of cards.
It really shouldn't be entered in the cost string IMO but in the description.

**Comment by crusopaul** [comment]
Dang, okay.

**Comment by bmos** [comment]
I think it would have worked though 🥇

**Comment by bmos** [comment]
I just did this to hopefully provide some info.
Might be worth specifying which character too haha
```
local function processItemCost(sItemCost, sItemName)
	if string.match(sItemCost, '%-') then
		ChatManager.SystemMessage('Item ' .. sItemName .. ' has an improper value.')

		return 0
	end

	local sTrimmedItemCost = sItemCost:gsub('[^0-9.-]', '')

	if sTrimmedItemCost then
		nTrimmedItemCost = tonumber(sTrimmedItemCost)
		for k,v in pairs(TEGlobals.tDenominations) do
			if string.match(sItemCost, k) then
				return nTrimmedItemCost * v
			end
		end
	end

	return 0
end
```
